# Render Blueprint for ML Web Application
# This file defines the infrastructure as code for deploying the ML web service on Render

services:
  # Main web service
  - type: web
    name: ml-webapp
    env: python
    # Build command to install dependencies
    buildCommand: pip install -r requirements.txt
    # Start command for the web service
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120
    # Environment variables
    envVars:
      - key: PYTHONUNBUFFERED
        value: true
      - key: PYTHONPATH
        value: /opt/render/project/src
    # Health check path
    healthCheckPath: /health
    # Auto-deploy from Git
    autoDeploy: true
    # Plan settings (free tier)
    plan: free
    # Region (choose the one closest to your users)
    region: oregon
    # Build environment variables (if needed)
    build:
      envVars:
        - key: PIP_DEFAULT_TIMEOUT
          value: '100'
        - key: PIPENV_TIMEOUT
          value: '1000'
        - key: PIPENV_NOSPIN
          value: '1'
